# Generated by Django 5.2.3 on 2025-06-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_itemlisting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
